version: '3'

services:
  reservation-form:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
  
  database:
    build: ./db
    ports:
      - '3306:3306'

  # database:
  #   image: mysql:5.7
  #   environment:
  #     MySQL_USER: 'root'
  #     MYSQL_ROOT_PASSWORD: ${DB_PW}
  #     MYSQL_DATABASE: 'reservation_db'
  #   volumes:
  #     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      

