version: '3'

services:
  reservation-form:
    build:
      context: .
      args:
        DB_PW: ${DB_PW}
        DB_USER: ${DB_USER}
        DB_DB: ${DB_DB}
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
  
  database:
    build:
      context: ./db
      args:
        DB_PW: ${DB_PW}
    ports:
      - '3306:3306'

  # database:
  #   image: mysql:5.7
  #   environment:
  #     MySQL_USER: 'root'
  #     MYSQL_ROOT_PASSWORD: ${DB_PW}
  #     MYSQL_DATABASE: 'reservation_db'
  #   volumes:
  #     - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      

